  alpine-qbittorrent-openvpn:
    volumes:
      - /download-path:/downloads
      - /srv/dev-disk-by-label-data/appdata/qbittorentVPN:/config"
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OPENVPN_PROVIDER=NordVPN
      - OPENVPN_CONFIG=us6767
      - OPENVPN_USERNAME=#ADD YOUR USERNAME HERE
      - OPENVPN_PASSWORD=#ADD YOUR PASSWORD HERE
      - PUID=1000
      - PGID=1000
      - LAN=192.168.0.0/24
    ports:
      - 8080:8080
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
