  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - BASE_URL=/ombi #optional
    volumes:
      - /srv/dev-disk-by-label-data/appdata/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
