  plex:
    image: ghcr.io/linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - VERSION=docker
    volumes:
      - /srv/dev-disk-by-label-data/appdata/plex:/config
      - /download-path:/media
    restart: unless-stopped
