 sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/New_York
        - UMASK_SET=022 #optional
    volumes:
        - /srv/dev-disk-by-label-data/appdata/sonarr:/config
        - /download-path:/media
    restart: unless-stopped
    ports: 
        - 8989:8989
